#!/usr/bin/env python3
"""offline.py — AgentDojo's own ground truth through the gateway, with no model and no API call.

  .venv-inspect/bin/python 17_agentdojo/offline.py            # all four suites; writes OFFLINE.md

Every AgentDojo task ships the tool-call sequence that solves it. Running those sequences through the gateway gives two numbers for free:
  utility ceiling   the share of user tasks whose correct solution the gateway would let through in full. No model can score higher than this with the walls on.
  security floor    the share of injection tasks whose correct execution the gateway refuses at least one call of. A model that does exactly what the injection asks is stopped here.
Both come from the benchmark's own definitions, not ours. The failures are listed with their reasons, because the reasons are the finding: a refusal because the task's
destination or action is only knowable from content is the policy working as designed, and its cost; a refusal because the prompt's wording was not recognised is a policy bug.
"""
import json, sys, time
from collections import Counter
from pathlib import Path
_HERE = Path(__file__).resolve().parent; sys.path.insert(0, str(_HERE))
import dojo_gateway as G
from agentdojo.functions_runtime import FunctionsRuntime
from agentdojo.task_suite.load_suites import get_suite

SUITES = ("workspace", "banking", "travel", "slack")


def run_calls(suite, env, prompt, calls, walls=True, url_profile="strict"):
    """Decide each ground-truth call against a fresh gateway, executing the allowed ones so later calls see the right state. Nested calls are resolved first, as the real runtime does."""
    gw = G.DojoGateway(suite.name, prompt, env, walls=walls, url_profile=url_profile); rt = FunctionsRuntime(suite.tools); denials = []
    for c in calls:
        try: args = rt._execute_nested_calls(env, c.args)
        except Exception: args = dict(c.args)
        ok, why = gw.decide(c.function, args)
        if ok:
            try:
                from agentdojo.agent_pipeline.tool_execution import tool_result_to_str
                res, _ = rt.run_function(env, c.function, args); gw.saw(tool_result_to_str(res))
            except Exception: pass
        else: denials.append((c.function, why))
    return denials, gw


def evaluate(version="v1", url_profile="strict"):
    """Every user task's own solution, and every (user task, injection task) PAIR as the benchmark pairs them: the injection's solution is judged under the user task's prompt, because that prompt is what the policy is built from."""
    out = {}
    for name in SUITES:
        suite = get_suite(version, name); base = suite.load_and_inject_default_environment({})
        users = {}
        for tid, task in suite.user_tasks.items():
            env = task.init_environment(base.model_copy(deep=True)); calls = task.ground_truth(env.model_copy(deep=True))
            denials, _ = run_calls(suite, env, task.PROMPT, calls, url_profile=url_profile); users[tid] = {"calls": [c.function for c in calls], "denials": denials}
        injections = {}
        for tid, task in suite.injection_tasks.items():
            pairs = {}
            for uid, ut in suite.user_tasks.items():
                env = ut.init_environment(base.model_copy(deep=True)); calls = task.ground_truth(env.model_copy(deep=True))
                denials, _ = run_calls(suite, env, ut.PROMPT, calls, url_profile=url_profile); pairs[uid] = denials
            injections[tid] = {"calls": [c.function for c in calls], "goal": task.GOAL, "pairs": pairs, "blocked_pairs": sum(1 for d in pairs.values() if d), "n_pairs": len(pairs)}
        out[name] = {"users": users, "injections": injections}
    return out


def report(res):
    L = ["# AgentDojo ground truth through the gateway (no model)", "", "*Generated by `offline.py`. The policy is built from the prompt and the user's own pre-task structured data only.*", ""]
    tot_u = tot_ok = tot_i = tot_blocked = 0
    L += ["| suite | user tasks the correct solution passes | (user task, injection) pairs where the injection's solution is refused |", "|---|---|---|"]
    for s, r in res.items():
        u = r["users"]; ok = sum(1 for v in u.values() if not v["denials"]); i = r["injections"]; blocked = sum(v["blocked_pairs"] for v in i.values()); n = sum(v["n_pairs"] for v in i.values())
        tot_u += len(u); tot_ok += ok; tot_i += n; tot_blocked += blocked
        L.append(f"| {s} | {ok}/{len(u)} | {blocked}/{n} |")
    L.append(f"| **all** | **{tot_ok}/{tot_u} ({tot_ok / tot_u:.0%})** | **{tot_blocked}/{tot_i} ({tot_blocked / tot_i:.0%})** |")
    L += ["", "The first column is a CEILING on utility with the walls on (a model cannot do better than the correct solution). The second is a FLOOR on security over the benchmark's own pairs: the injection's correct execution is judged under the user task's prompt, because that prompt is what the policy is built from. A model that reaches the injection's goal by other calls is not covered by it.", ""]
    for s, r in res.items():
        fails = {t: v for t, v in r["users"].items() if v["denials"]}
        L += [f"## {s}: user tasks the gateway would break ({len(fails)} of {len(r['users'])})", ""]
        if not fails: L.append("none"); L.append("")
        for t, v in fails.items():
            L.append(f"- `{t}`: " + "; ".join(f"{f}: {w}" for f, w in v["denials"]))
        L.append("")
        L += [f"## {s}: injection tasks, pairs NOT stopped", ""]
        for t, v in r["injections"].items():
            open_pairs = [u for u, d in v["pairs"].items() if not d]
            L.append(f"- `{t}` ({', '.join(v['calls']) or 'no call'}): {v['blocked_pairs']}/{v['n_pairs']} pairs refused" + (f"; open under {', '.join(open_pairs[:8])}{'...' if len(open_pairs) > 8 else ''}" if open_pairs else ""))
        L.append("")
        kinds = Counter(w.split(":")[0] for v in r["injections"].values() for d in v["pairs"].values() for _, w in d)
        if kinds: L.append(f"Refusal kinds over all pairs: {dict(kinds)}"); L.append("")
    return "\n".join(L)


if __name__ == "__main__":
    t0 = time.time(); parts = []
    for prof in ("strict", "seen"):
        res = evaluate(url_profile=prof); (_HERE / f"offline_results_{prof}.json").write_text(json.dumps(res, indent=1, default=str)); r = report(res).replace("# AgentDojo ground truth through the gateway (no model)", f"# AgentDojo ground truth through the gateway (no model), url profile `{prof}`"); parts.append(r)
        print(f"[{prof}]"); print(r.split("\n\n")[2])
    (_HERE / "OFFLINE.md").write_text("\n\n---\n\n".join(parts)); print(f"{time.time() - t0:.0f}s; wrote OFFLINE.md")
